from atrivon.domain.models import (
    Goal,
    Plan,
    Subgoal,
    Task,
)
from atrivon.domain.states import PlanState


class Planner:
    """
    The Planner transforms an Atrivon Goal into a structured Plan.

    The Planner is responsible for:
    - Understanding the goal category
    - Creating subgoals
    - Creating tasks
    - Building a versioned Plan

    The Planner does not own the Goal lifecycle.
    The Kernel coordinates the Goal lifecycle.
    """

    def __init__(self):
        print("Planner module loaded.")

    def create_plan(
        self,
        goal: Goal,
    ) -> Plan:
        """
        Create a canonical Plan for an Atrivon Goal.
        """

        if not isinstance(
            goal,
            Goal,
        ):
            raise TypeError(
                "Planner.create_plan() requires a Goal object."
            )

        objective = goal.objective.strip()
        normalized_objective = objective.lower()

        print(
            f"\nCreating plan for goal: "
            f"{objective}"
        )

        subgoal_definitions = (
            self._build_subgoal_definitions(
                normalized_objective
            )
        )

        plan = Plan(
            goal_id=goal.id,
            version=1,
            state=PlanState.PROPOSED,
            rationale=(
                "Plan generated by the Atrivon Planner "
                "from the current goal objective."
            ),
        )

        for subgoal_name, tasks in subgoal_definitions:
            subgoal = Subgoal(
                name=subgoal_name
            )

            for task_title in tasks:
                task = Task(
                    title=task_title
                )

                subgoal.add_task(
                    task
                )

            plan.add_subgoal(
                subgoal
            )

        self._display_plan(
            goal,
            plan,
        )

        return plan

    def _build_subgoal_definitions(
        self,
        normalized_objective: str,
    ) -> list[tuple[str, list[str]]]:
        """
        Determine the appropriate subgoals and tasks
        for the current goal objective.

        This is the current deterministic planning layer.
        It is intentionally structured so that it can later
        evolve into more advanced dynamic planning.
        """

        if any(
            keyword in normalized_objective
            for keyword in [
                "website",
                "web app",
                "web application",
            ]
        ):
            return [
                (
                    "Define the website objective",
                    [
                        "Understand the website requirements",
                        "Define the target users",
                        "Define the desired outcomes",
                    ],
                ),
                (
                    "Design the website",
                    [
                        "Design the website structure",
                        "Design the user experience",
                        "Define the required functionality",
                    ],
                ),
                (
                    "Build the website",
                    [
                        "Implement the required functionality",
                        "Integrate required systems",
                        "Prepare the website for testing",
                    ],
                ),
                (
                    "Launch and improve the website",
                    [
                        "Test the website",
                        "Deploy the website",
                        "Monitor performance and improve the experience",
                    ],
                ),
            ]

        if any(
            keyword in normalized_objective
            for keyword in [
                "online business",
                "business",
                "startup",
                "company",
            ]
        ):
            return [
                (
                    "Validate the business opportunity",
                    [
                        "Understand the business objective",
                        "Identify the target market",
                        "Identify customer needs",
                        "Analyze the competitive landscape",
                    ],
                ),
                (
                    "Design the business model",
                    [
                        "Define the value proposition",
                        "Define the products or services",
                        "Define the pricing model",
                        "Define the operating model",
                    ],
                ),
                (
                    "Build the business foundation",
                    [
                        "Define the required systems",
                        "Prepare the operational structure",
                        "Build the required technology",
                        "Prepare the launch strategy",
                    ],
                ),
                (
                    "Launch and improve the business",
                    [
                        "Launch the business",
                        "Measure the results",
                        "Identify problems and opportunities",
                        "Improve based on real-world feedback",
                    ],
                ),
            ]

        if any(
            keyword in normalized_objective
            for keyword in [
                "analyze",
                "analysis",
                "research",
            ]
        ):
            return [
                (
                    "Define the research objective",
                    [
                        "Understand the analysis objective",
                        "Identify the required information",
                        "Define the desired outcome",
                    ],
                ),
                (
                    "Collect and organize information",
                    [
                        "Collect relevant information",
                        "Validate the information",
                        "Organize the information",
                    ],
                ),
                (
                    "Analyze the information",
                    [
                        "Identify important patterns",
                        "Identify risks and opportunities",
                        "Form conclusions",
                    ],
                ),
                (
                    "Produce recommendations",
                    [
                        "Summarize the findings",
                        "Develop recommendations",
                        "Present the final analysis",
                    ],
                ),
            ]

        if any(
            keyword in normalized_objective
            for keyword in [
                "learn",
                "study",
                "understand",
                "teach",
            ]
        ):
            return [
                (
                    "Define the learning objective",
                    [
                        "Understand the subject",
                        "Define the learning outcome",
                        "Assess the current level of knowledge",
                    ],
                ),
                (
                    "Build the learning path",
                    [
                        "Identify the key concepts",
                        "Organize the concepts in a logical sequence",
                        "Create a structured learning plan",
                    ],
                ),
                (
                    "Practice and apply knowledge",
                    [
                        "Study the key concepts",
                        "Practice the concepts",
                        "Apply the knowledge to real problems",
                    ],
                ),
                (
                    "Evaluate and improve",
                    [
                        "Evaluate understanding",
                        "Identify knowledge gaps",
                        "Improve weak areas",
                    ],
                ),
            ]

        return [
            (
                "Understand the goal",
                [
                    "Clarify the desired outcome",
                    "Identify the requirements",
                    "Identify constraints and assumptions",
                ],
            ),
            (
                "Design the approach",
                [
                    "Break the goal into smaller objectives",
                    "Identify dependencies",
                    "Determine the order of work",
                ],
            ),
            (
                "Prepare for execution",
                [
                    "Identify required resources",
                    "Identify potential risks",
                    "Prepare the plan for reasoning and execution",
                ],
            ),
        ]

    def _display_plan(
        self,
        goal: Goal,
        plan: Plan,
    ) -> None:
        """
        Display a canonical Plan in a readable format.
        """

        print("\nPlan Created:")
        print(
            f"Goal: {goal.objective}"
        )
        print(
            f"Plan Version: {plan.version}"
        )
        print(
            f"Plan State: {plan.state.value}"
        )

        for subgoal_number, subgoal in enumerate(
            plan.subgoals,
            start=1,
        ):
            print(
                f"\n{subgoal_number}. "
                f"{subgoal.name}"
            )

            for task_number, task in enumerate(
                subgoal.tasks,
                start=1,
            ):
                print(
                    f"   "
                    f"{subgoal_number}.{task_number}. "
                    f"{task.title}"
                )